CREATE DATABASE chuyende_qltaisan
USE chuyende_qltaisan

CREATE TABLE LOAITAISAN
(
	MALOAI INT IDENTITY (1,1),
	TENLOAI NVARCHAR (20) NOT NULL,
	CONSTRAINT [PK_LOAITAISAN] PRIMARY KEY (MALOAI)
)

CREATE TABLE DONVITINH
(
	MADONVITINH INT IDENTITY (1,1),
	TENDONVITINH NVARCHAR (10) NOT NULL,
	CONSTRAINT [PK_DONVITINH] PRIMARY KEY (MADONVITINH)
)

CREATE TABLE TAISAN
(
	MATAISAN INT IDENTITY (1,1),
	MALOAI INT NOT NULL,
	TENTAISAN NVARCHAR (20) NOT NULL,
	MADONVITINH INT NOT NULL,
	GIA VARCHAR (20) NOT NULL,
	CONSTRAINT [PK_TAISAN] PRIMARY KEY (MATAISAN),
	CONSTRAINT [FK_TAISAN_LOAITAISAN] FOREIGN KEY (MALOAI) REFERENCES [LOAITAISAN] (MALOAI),
	CONSTRAINT [FK_TAISAN_DONVITINH] FOREIGN KEY (MADONVITINH) REFERENCES [DONVITINH] (MADONVITINH)
)

CREATE TABLE NHAPTS 
(
	MANHAPTS INT IDENTITY (1,1),
	NGAYNHAP DATETIME NOT NULL,
	CONSTRAINT [PK_NHAPTS] PRIMARY KEY (MANHAPTS)
)

CREATE TABLE CHITIETNHAPTS
(
	MACHITIETNHAP INT IDENTITY (1,1),
	NHANVIEN NVARCHAR (20) NOT NULL,
	MANHAPTS INT NOT NULL,
	MATAISAN INT NOT NULL,
	SOLUONG VARCHAR (100),
	CONSTRAINT [PK_CHITIETNHAPTS] PRIMARY KEY (MACHITIETNHAP),
	CONSTRAINT [FK_CHITIETNHAPTS_NHAPTS] FOREIGN KEY (MANHAPTS) REFERENCES [NHAPTS] (MANHAPTS),
	CONSTRAINT [FK_CHITIETNHAPTS_TAISAN] FOREIGN KEY (MATAISAN) REFERENCES [TAISAN] (MATAISAN)
)

CREATE TABLE TINHTRANG
(
	MATINHTRANG INT IDENTITY (1,1),
	TINHTRANG NVARCHAR (10) NOT NULL
	CONSTRAINT [PK_TINHTRANG] PRIMARY KEY (MATINHTRANG)
)

CREATE TABLE KIEMKE
(
	MAKIEMKE INT IDENTITY (1,1),
	NGAYKIEMKE DATETIME NOT NULL,
	MATAISAN INT NOT NULL,
	NHANVIEN NVARCHAR (20) NOT NULL,
	MATINHTRANG INT NOT NULL,
	CONSTRAINT [PK_KIEMKE] PRIMARY KEY (MAKIEMKE),
	CONSTRAINT [FK_KIEMKE_TAISAN] FOREIGN KEY (MATAISAN) REFERENCES [TAISAN] (MATAISAN),
	CONSTRAINT [FK_KIEMKE_MATINHTRANG] FOREIGN KEY (MATINHTRANG) REFERENCES [TINHTRANG] (MATINHTRANG)
)

CREATE TABLE THANHLY
(
	MATHANHLY INT IDENTITY (1,1),
	MATAISAN INT NOT NULL,
	GIATRITHANHLY VARCHAR (100) NOT NULL,
	SOLUONG VARCHAR (100) NOT NULL,
	CONSTRAINT [PK_THANHLY] PRIMARY KEY (MATHANHLY),
	CONSTRAINT [FK_THANHLY_TAISAN] FOREIGN KEY (MATAISAN) REFERENCES [TAISAN] (MATAISAN)
)