//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAPT
    {
        public int MACHITIETNHAP { get; set; }
        public string NHANVIEN { get; set; }
        public int MANHAPTS { get; set; }
        public int MATAISAN { get; set; }
        public string SOLUONG { get; set; }
    
        public virtual NHAPT NHAPT { get; set; }
        public virtual TAISAN TAISAN { get; set; }
    }
}
