//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIEMKE
    {
        public int MAKIEMKE { get; set; }
        public System.DateTime NGAYKIEMKE { get; set; }
        public int MATAISAN { get; set; }
        public string NHANVIEN { get; set; }
        public int MATINHTRANG { get; set; }
    
        public virtual TINHTRANG TINHTRANG { get; set; }
        public virtual TAISAN TAISAN { get; set; }
    }
}
