//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAITAISAN
    {
        public LOAITAISAN()
        {
            this.TAISANs = new HashSet<TAISAN>();
        }
    
        public int MALOAI { get; set; }
        public string TENLOAI { get; set; }
    
        public virtual ICollection<TAISAN> TAISANs { get; set; }
    }
}
