//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPT
    {
        public NHAPT()
        {
            this.CHITIETNHAPTS = new HashSet<CHITIETNHAPT>();
        }
    
        public int MANHAPTS { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
    
        public virtual ICollection<CHITIETNHAPT> CHITIETNHAPTS { get; set; }
    }
}
