//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qltaisan : DbContext
    {
        public qltaisan()
            : base("name=qltaisan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETNHAPT> CHITIETNHAPTS { get; set; }
        public virtual DbSet<DONVITINH> DONVITINHs { get; set; }
        public virtual DbSet<KIEMKE> KIEMKEs { get; set; }
        public virtual DbSet<LOAITAISAN> LOAITAISANs { get; set; }
        public virtual DbSet<NHAPT> NHAPTS { get; set; }
        public virtual DbSet<TAISAN> TAISANs { get; set; }
        public virtual DbSet<THANHLY> THANHLies { get; set; }
        public virtual DbSet<TINHTRANG> TINHTRANGs { get; set; }
    }
}
