//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAISAN
    {
        public TAISAN()
        {
            this.CHITIETNHAPTS = new HashSet<CHITIETNHAPT>();
            this.KIEMKEs = new HashSet<KIEMKE>();
            this.THANHLies = new HashSet<THANHLY>();
        }
    
        public int MATAISAN { get; set; }
        public int MALOAI { get; set; }
        public string TENTAISAN { get; set; }
        public int MADONVITINH { get; set; }
        public string GIA { get; set; }
    
        public virtual ICollection<CHITIETNHAPT> CHITIETNHAPTS { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual ICollection<KIEMKE> KIEMKEs { get; set; }
        public virtual LOAITAISAN LOAITAISAN { get; set; }
        public virtual ICollection<THANHLY> THANHLies { get; set; }
    }
}
