//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qltaisan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANG
    {
        public TINHTRANG()
        {
            this.KIEMKEs = new HashSet<KIEMKE>();
        }
    
        public int MATINHTRANG { get; set; }
        public string TINHTRANG1 { get; set; }
    
        public virtual ICollection<KIEMKE> KIEMKEs { get; set; }
    }
}
